@MindCalm.Services.Identity.API_HostAddress = http://localhost:5012
@MindCalm = http://localhost:5012

### Login as Guest
POST {{MindCalm}}/api/auth/guest
Accept: application/json

### 2. Register a Brand New User (Direct Registration)
POST {{MindCalm}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "userId": null,
  "email": "john.doe@mindcalm.com",
  "password": "SuperSecretPassword1!"
}

### 3. Promote an Existing Guest to Registered
# Step 1: Run the Guest Login request first to get a token and UserId.
# Step 2: Copy that UserId and replace the string below!
POST {{MindCalm}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "userId": "019c90d6-2cc7-7bad-b1f7-ea2980cb5509",
  "email": "upgraded.guest@mindcalm.com",
  "password": "SuperSecretPassword1!"
}

### 4. Test FluentValidation Failure (Should return 400 Bad Request)
# This sends a bad email and a weak password to trigger the MediatR Pipeline!
POST {{MindCalm}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "userId": "019c90d6-2cc7-7bad-b1f7-ea2980cb5509",
  "email": "not-a-valid-email",
  "password": "weak"
}

### 5. Test the Standard Login (Make sure you use the email/password you registered earlier!)
POST {{MindCalm}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "upgraded.guest@mindcalm.com",
  "password": "SuperSecretPassword1!"
}

### 6. JWT TEST 
GET {{MindCalm}}/api/auth/me
Accept: application/json